#!/bin/sh

make distclean
find . -name Makefile.in -exec rm -f {} \;
find . -name Makefile -exec rm -f {} \;
find . -name "*~" -exec rm -f {} \;
find . -name ".#*" -exec rm -f {} \;
rm -rf intl
rm -rf autom4te.cache
rm -f po/Makefile.in.in po/*.gmo po/Makevars.template po/Rules-quot po/boldquot.sed po/en@boldquot.header po/en@quot.header po/insert-header.sin po/quot.sed po/remove-potcdate.sin config.log config.cache config.status config.h gftp.spec stamp-h stamp-h.in ABOUT-NLS INSTALL config.guess config.rpath config.status config.sub configure install-sh missing mkinstalldirs

